### ISSUE TITLE
Error cant find module

### ISSUE THREAD

**Issue by pinguxx** [WebReflection/asbundle#17]
using this file
```
import HyperHTMLElement from 'hyperhtml-element/esm';
const { wire } = HyperHTMLElement;
```
then doing asbundle main.js
i get
```
module.js:550
    throw err;
    ^

Error: Cannot find module 'hyperhtml-element/esm'
    at Function.Module._resolveFilename (module.js:548:15)
```
any idea?

**Comment by WebReflection** [comment]
as bundle expect paths you can transform via CJS, in this case you want to import either `hyperhtml-element` or `hyperhtml-element/cjs`.

For anything more complex I suggest rollback 👋

**Comment by pinguxx** [comment]
rollup i assume?, im using rollup i was just trying to generate a cjs version of the files easily... but probably not required since they are custom elements..........

**Comment by WebReflection** [comment]
Yes, rollup, stupid phone
